### ISSUE TITLE
Recipes with Rock/Celestial Crystals as an ingredient cannot be automated

### ISSUE THREAD

**Issue by SheReyy** [TheLMiffy1111/PackagedAstral#2]
Forge 36.2.34
PackagedAstral-1.16.5-2.0.0.1.jar
astralsorcery-1.16.5-1.14.1.jar

Pretty much what the title says. When I place a recipe in my ME system, it will be recognized, but as soon as I try to craft it, even tho I have rock crystals, the system won't see them.
![image](https://user-images.githubusercontent.com/91336389/219463597-967164eb-af9d-4bd2-941a-d2ee99becc6a.png)
![image](https://user-images.githubusercontent.com/91336389/219463685-8247251e-1ba9-4f82-821c-892164afc5eb.png)
![image](https://user-images.githubusercontent.com/91336389/219463742-5660e186-545a-4927-a551-efbdc01af2f2.png)

**Comment by TheLMiffy1111** [comment]
AE2 has this limitation where the items require an exact nbt match to be used in autocrafting. Since rock crystals have nbt data for their stats, unless you have something that manufactures identical rock crystals, you cannot use them in AE2 autocrafting.

**Comment by SheReyy** [comment]
Understood. Thanks a lot
