### ISSUE TITLE
Starlight Package Crafting Altar not working mc 1.12.2

### ISSUE THREAD

**Issue by IDarKIAnghold** [TheLMiffy1111/PackagedAstral#3]
Good day. The problem is the same as the title. There is such a design. The most common Starlight Altar design, while the Starlight Altar itself works, but the Starlight Package Crafting Altar. 

![image](https://github.com/TheLMiffy1111/PackagedAstral/assets/97733841/a0126c98-ea9f-4658-bea4-eee7dcad5cb2)

Starlight Package Crafting Altar
![image](https://github.com/TheLMiffy1111/PackagedAstral/assets/97733841/6976d6c6-555e-4038-b83d-d020000844bf)

Starlight Altar:
![image](https://github.com/TheLMiffy1111/PackagedAstral/assets/97733841/8ebcbe1c-8030-497e-822d-7c1269ec46e9)

**Comment by TheLMiffy1111** [comment]
Should be fixed, try updating to 1.0.2.8 and re-placing the altar

**Comment by IDarKIAnghold** [comment]
Thanks for the quick fix
