### ISSUE TITLE
Buildscript includes incorrect optional dependency on CurseForge

### ISSUE THREAD

**Issue by WaitingIdly** [TheLMiffy1111/PackagedAstral#5]
## Situation

Currently, the `build.gradle` includes the following line: https://github.com/TheLMiffy1111/PackagedAstral/blob/0140f24d95db52aae6680c98802a170ba7528f91/build.gradle#L173 which specifies that `thaumic-energistics` adds optional compatibility to `PackagedAstral`. This has been the case since Feb 19, 2024, with the release of [1.12.2-1.0.2.11](https://www.curseforge.com/minecraft/mc-mods/packagedastral/files/5121337/dependencies).

## Problem 

`thaumic-energistics` doesn't actually add compat, this was likely a mistake when copying the buildscript. This issue applies to both the `1.12` and `1.16` branches

## Solution

Remove the modid from the `optional` list, and edit the most recent releases on CurseForge.

**Comment by TheLMiffy1111** [comment]
Done
